version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "monthly"

  # PHP Images
  - package-ecosystem: "docker"
    directory: "/php/7.4/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/php/8.0/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/php/8.1/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/php/8.2/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # WordPress Images
  - package-ecosystem: "docker"
    directory: "/wp/php7.4/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: ghcr.io/syntatis/php

  - package-ecosystem: "docker"
    directory: "/wp/php8.0/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: ghcr.io/syntatis/php

  - package-ecosystem: "docker"
    directory: "/wp/php8.1/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: ghcr.io/syntatis/php

  - package-ecosystem: "docker"
    directory: "/wp/php8.2/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: ghcr.io/syntatis/php
