name: wp

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TOKEN_PACKAGE:
        required: true
  push:
    branches:
      - main
    paths:
      - ./.github/workflows/wp.yml
      - ./wp/**/Dockerfile
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - ./.github/workflows/wp.yml
      - ./wp/**/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        version: ["7.4", "8.0", "8.1", "8.2"]

    env:
      IMAGE_FILE: ./wp/php${{ matrix.version }}/Dockerfile
      IMAGE_REGISTRY: ghcr.io
      IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/wp:php${{ matrix.version }}-fpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          file: ${{ env.IMAGE_FILE }}
          tags: ${{ env.IMAGE_TAG }}

      - name: Test run image
        run: |
          ver=$(docker run --rm ${{ env.IMAGE_TAG }} php -v | grep -o "^PHP [0-9].[0-9]");

          if [ "$ver" == "PHP ${{ matrix.version }}" ];
          then
            echo $ver;
          else
            exit 1;
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_TAG }}

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          file: ${{ env.IMAGE_FILE }}
          tags: ${{ env.IMAGE_TAG }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
